// Copyright (c) 2025 Skyza (meetleev)
// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every((MapEntry<Object?, Object?> entry) =>
            (b as Map<Object?, Object?>).containsKey(entry.key) &&
            _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}

enum LogLevel {
  verbose,
  debug,
  info,
  warn,
  error,
  off,
}

enum PushStatus {
  start,
  pause,
  stop,
  unknown,
}

enum NotificationStatus {
  open,
  close,
  unknown,
}

sealed class PlatformEvent {}

class SetPushTimeEvent extends PlatformEvent {
  SetPushTimeEvent({
    this.pushTime,
    required this.responseCode,
  });

  String? pushTime;

  int responseCode;

  List<Object?> _toList() {
    return <Object?>[
      pushTime,
      responseCode,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SetPushTimeEvent decode(Object result) {
    result as List<Object?>;
    return SetPushTimeEvent(
      pushTime: result[0] as String?,
      responseCode: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SetPushTimeEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PushStatusEvent extends PlatformEvent {
  PushStatusEvent({
    required this.responseCode,
    required this.status,
  });

  int responseCode;

  PushStatus status;

  List<Object?> _toList() {
    return <Object?>[
      responseCode,
      status,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PushStatusEvent decode(Object result) {
    result as List<Object?>;
    return PushStatusEvent(
      responseCode: result[0]! as int,
      status: result[1]! as PushStatus,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PushStatusEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class NotificationStatusEvent extends PlatformEvent {
  NotificationStatusEvent({
    required this.responseCode,
    required this.status,
  });

  int responseCode;

  NotificationStatus status;

  List<Object?> _toList() {
    return <Object?>[
      responseCode,
      status,
    ];
  }

  Object encode() {
    return _toList();
  }

  static NotificationStatusEvent decode(Object result) {
    result as List<Object?>;
    return NotificationStatusEvent(
      responseCode: result[0]! as int,
      status: result[1]! as NotificationStatus,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NotificationStatusEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class RegisterEvent extends PlatformEvent {
  RegisterEvent({
    required this.responseCode,
    this.token,
    this.packageName,
    this.miniProgramPkg,
  });

  int responseCode;

  /// 注册id/token
  String? token;

  /// 当前注册失败的应用包名，如果是应用注册，则返回应用注册包名，如果是为快应用做接口请求，则这里返回的是快应用中心的包名
  String? packageName;

  /// 当前注册失败的快应用包名
  String? miniProgramPkg;

  List<Object?> _toList() {
    return <Object?>[
      responseCode,
      token,
      packageName,
      miniProgramPkg,
    ];
  }

  Object encode() {
    return _toList();
  }

  static RegisterEvent decode(Object result) {
    result as List<Object?>;
    return RegisterEvent(
      responseCode: result[0]! as int,
      token: result[1] as String?,
      packageName: result[2] as String?,
      miniProgramPkg: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RegisterEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class UnregisterEvent extends PlatformEvent {
  UnregisterEvent({
    required this.responseCode,
    this.packageName,
    this.miniProgramPkg,
  });

  int responseCode;

  /// 当前注册失败的应用包名，如果是应用注册，则返回应用注册包名，如果是为快应用做接口请求，则这里返回的是快应用中心的包名
  String? packageName;

  /// 当前注册失败的快应用包名
  String? miniProgramPkg;

  List<Object?> _toList() {
    return <Object?>[
      responseCode,
      packageName,
      miniProgramPkg,
    ];
  }

  Object encode() {
    return _toList();
  }

  static UnregisterEvent decode(Object result) {
    result as List<Object?>;
    return UnregisterEvent(
      responseCode: result[0]! as int,
      packageName: result[1] as String?,
      miniProgramPkg: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UnregisterEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// 异常处理的回调
class ErrorEvent extends PlatformEvent {
  ErrorEvent({
    required this.code,
    required this.message,
    required this.packageName,
    required this.miniProgramPkg,
  });

  int code;

  /// 错误信息
  String message;

  /// 当前注册失败的应用包名，如果是应用注册，则返回应用注册包名，如果是为快应用做接口请求，则这里返回的是快应用中心的包名
  String packageName;

  /// 当前注册失败的快应用包名
  String miniProgramPkg;

  List<Object?> _toList() {
    return <Object?>[
      code,
      message,
      packageName,
      miniProgramPkg,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ErrorEvent decode(Object result) {
    result as List<Object?>;
    return ErrorEvent(
      code: result[0]! as int,
      message: result[1]! as String,
      packageName: result[2]! as String,
      miniProgramPkg: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ErrorEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is LogLevel) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is PushStatus) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is NotificationStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is SetPushTimeEvent) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PushStatusEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is NotificationStatusEvent) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is RegisterEvent) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is UnregisterEvent) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is ErrorEvent) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : LogLevel.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PushStatus.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NotificationStatus.values[value];
      case 132:
        return SetPushTimeEvent.decode(readValue(buffer)!);
      case 133:
        return PushStatusEvent.decode(readValue(buffer)!);
      case 134:
        return NotificationStatusEvent.decode(readValue(buffer)!);
      case 135:
        return RegisterEvent.decode(readValue(buffer)!);
      case 136:
        return UnregisterEvent.decode(readValue(buffer)!);
      case 137:
        return ErrorEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec =
    StandardMethodCodec(_PigeonCodec());

class PushInterface {
  /// Constructor for [PushInterface].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  PushInterface(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> setLogLevel(LogLevel level) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.setLogLevel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[level]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<LogLevel> getLogLevel() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.getLogLevel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as LogLevel?)!;
    }
  }

  /// 初始化push服务
  Future<void> initialize(bool oppoLogEnabled) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[oppoLogEnabled]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 恢复接收MSP服务推送的消息，这时服务器会把暂停时期的推送消息重新推送过来
  Future<void> resumePush() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.resumePush$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 暂停接收MSP服务推送的消息
  Future<void> pausePush() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.pausePush$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 获取MSP推送服务状态
  Future<void> getPushStatus() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.getPushStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 设置允许推送时间 API,  weekDays 周日为0,周一为1,以此类推, startHour 开始时间,24小时制, endHour 结束时间,24小时制
  Future<void> setPushTime({
    required List<int> weekDays,
    required int startHour,
    required int startMin,
    required int endHour,
    required int endMin,
  }) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.setPushTime$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel
        .send(<Object?>[weekDays, startHour, startMin, endHour, endMin]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 获取当前设备的当前应用的唯一标识，后台可基于此标识发送通知
  Future<String> getRegId() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.getRegId$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  /// 注册push，获取申请的regId
  Future<void> registerToken(
      {required String appKey, required String appSecret}) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.registerToken$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[appKey, appSecret]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 解注册push，关闭push功能
  Future<void> unregisterToken() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.unregisterToken$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 打开通知栏设置界面
  Future<void> openNotificationSetting() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.openNotificationSetting$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 获取通知栏状态
  Future<void> getNotificationStatus() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.getNotificationStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 打开应用内通知
  Future<NotificationStatus> enableAppNotificationSwitch() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.enableAppNotificationSwitch$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NotificationStatus?)!;
    }
  }

  /// 关闭应用内通知
  Future<NotificationStatus> disableAppNotificationSwitch() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.disableAppNotificationSwitch$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NotificationStatus?)!;
    }
  }

  /// 获取应用内通知开关
  Future<NotificationStatus> getAppNotificationSwitch() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.getAppNotificationSwitch$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NotificationStatus?)!;
    }
  }

  /// 用于判断当前系统是否支持push服务
  Future<bool> isSupport() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.oppo_push.PushInterface.isSupport$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }
}

/// 所有回调都需要根据responseCode来判断操作是否成功，0代表成功,其他代码失败，失败具体原因可以查阅附录中的错误码列表, https://open.oppomobile.com/documentation/page/info?id=11224
Stream<PlatformEvent> streamEvents({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel streamEventsChannel = EventChannel(
      'dev.flutter.pigeon.oppo_push.PushCallBackEventChannel.streamEvents$instanceName',
      pigeonMethodCodec);
  return streamEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as PlatformEvent;
  });
}
