// Copyright (c) 2025 Skyza (meetleev)
// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class LogLevel(val raw: Int) {
  VERBOSE(0),
  DEBUG(1),
  INFO(2),
  WARN(3),
  ERROR(4),
  OFF(5);

  companion object {
    fun ofRaw(raw: Int): LogLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PushStatus(val raw: Int) {
  START(0),
  PAUSE(1),
  STOP(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): PushStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class NotificationStatus(val raw: Int) {
  OPEN(0),
  CLOSE(1),
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): NotificationStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class PlatformEvent 
/** Generated class from Pigeon that represents data sent in messages. */
data class SetPushTimeEvent (
  val pushTime: String? = null,
  val responseCode: Long
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SetPushTimeEvent {
      val pushTime = pigeonVar_list[0] as String?
      val responseCode = pigeonVar_list[1] as Long
      return SetPushTimeEvent(pushTime, responseCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      pushTime,
      responseCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SetPushTimeEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PushStatusEvent (
  val responseCode: Long,
  val status: PushStatus
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PushStatusEvent {
      val responseCode = pigeonVar_list[0] as Long
      val status = pigeonVar_list[1] as PushStatus
      return PushStatusEvent(responseCode, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      responseCode,
      status,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PushStatusEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NotificationStatusEvent (
  val responseCode: Long,
  val status: NotificationStatus
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NotificationStatusEvent {
      val responseCode = pigeonVar_list[0] as Long
      val status = pigeonVar_list[1] as NotificationStatus
      return NotificationStatusEvent(responseCode, status)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      responseCode,
      status,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is NotificationStatusEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RegisterEvent (
  val responseCode: Long,
  /** 注册id/token */
  val token: String? = null,
  /** 当前注册失败的应用包名，如果是应用注册，则返回应用注册包名，如果是为快应用做接口请求，则这里返回的是快应用中心的包名 */
  val packageName: String? = null,
  /** 当前注册失败的快应用包名 */
  val miniProgramPkg: String? = null
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegisterEvent {
      val responseCode = pigeonVar_list[0] as Long
      val token = pigeonVar_list[1] as String?
      val packageName = pigeonVar_list[2] as String?
      val miniProgramPkg = pigeonVar_list[3] as String?
      return RegisterEvent(responseCode, token, packageName, miniProgramPkg)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      responseCode,
      token,
      packageName,
      miniProgramPkg,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RegisterEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UnregisterEvent (
  val responseCode: Long,
  /** 当前注册失败的应用包名，如果是应用注册，则返回应用注册包名，如果是为快应用做接口请求，则这里返回的是快应用中心的包名 */
  val packageName: String? = null,
  /** 当前注册失败的快应用包名 */
  val miniProgramPkg: String? = null
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UnregisterEvent {
      val responseCode = pigeonVar_list[0] as Long
      val packageName = pigeonVar_list[1] as String?
      val miniProgramPkg = pigeonVar_list[2] as String?
      return UnregisterEvent(responseCode, packageName, miniProgramPkg)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      responseCode,
      packageName,
      miniProgramPkg,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is UnregisterEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * 异常处理的回调
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ErrorEvent (
  val code: Long,
  /** 错误信息 */
  val message: String,
  /** 当前注册失败的应用包名，如果是应用注册，则返回应用注册包名，如果是为快应用做接口请求，则这里返回的是快应用中心的包名 */
  val packageName: String,
  /** 当前注册失败的快应用包名 */
  val miniProgramPkg: String
) : PlatformEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ErrorEvent {
      val code = pigeonVar_list[0] as Long
      val message = pigeonVar_list[1] as String
      val packageName = pigeonVar_list[2] as String
      val miniProgramPkg = pigeonVar_list[3] as String
      return ErrorEvent(code, message, packageName, miniProgramPkg)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      message,
      packageName,
      miniProgramPkg,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ErrorEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return MessagesPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LogLevel.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PushStatus.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NotificationStatus.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SetPushTimeEvent.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PushStatusEvent.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NotificationStatusEvent.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegisterEvent.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UnregisterEvent.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ErrorEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LogLevel -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is PushStatus -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is NotificationStatus -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is SetPushTimeEvent -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PushStatusEvent -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is NotificationStatusEvent -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is RegisterEvent -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is UnregisterEvent -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ErrorEvent -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val MessagesPigeonMethodCodec = StandardMethodCodec(MessagesPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface PushInterface {
  fun setLogLevel(level: LogLevel, callback: (Result<Unit>) -> Unit)
  fun getLogLevel(callback: (Result<LogLevel>) -> Unit)
  /** 初始化push服务 */
  fun initialize(oppoLogEnabled: Boolean)
  /** 恢复接收MSP服务推送的消息，这时服务器会把暂停时期的推送消息重新推送过来 */
  fun resumePush()
  /** 暂停接收MSP服务推送的消息 */
  fun pausePush()
  /** 获取MSP推送服务状态 */
  fun getPushStatus()
  /** 设置允许推送时间 API,  weekDays 周日为0,周一为1,以此类推, startHour 开始时间,24小时制, endHour 结束时间,24小时制 */
  fun setPushTime(weekDays: List<Long>, startHour: Long, startMin: Long, endHour: Long, endMin: Long)
  /** 获取当前设备的当前应用的唯一标识，后台可基于此标识发送通知 */
  fun getRegId(callback: (Result<String>) -> Unit)
  /** 注册push，获取申请的regId */
  fun registerToken(appKey: String, appSecret: String)
  /** 解注册push，关闭push功能 */
  fun unregisterToken()
  /** 打开通知栏设置界面 */
  fun openNotificationSetting()
  /** 获取通知栏状态 */
  fun getNotificationStatus()
  /** 打开应用内通知 */
  fun enableAppNotificationSwitch(callback: (Result<NotificationStatus>) -> Unit)
  /** 关闭应用内通知 */
  fun disableAppNotificationSwitch(callback: (Result<NotificationStatus>) -> Unit)
  /** 获取应用内通知开关 */
  fun getAppNotificationSwitch(callback: (Result<NotificationStatus>) -> Unit)
  /** 用于判断当前系统是否支持push服务 */
  fun isSupport(callback: (Result<Boolean>) -> Unit)

  companion object {
    /** The codec used by PushInterface. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `PushInterface` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: PushInterface?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.setLogLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] as LogLevel
            api.setLogLevel(levelArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                reply.reply(MessagesPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.getLogLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getLogLevel{ result: Result<LogLevel> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val oppoLogEnabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.initialize(oppoLogEnabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.resumePush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.resumePush()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.pausePush$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.pausePush()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.getPushStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.getPushStatus()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.setPushTime$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val weekDaysArg = args[0] as List<Long>
            val startHourArg = args[1] as Long
            val startMinArg = args[2] as Long
            val endHourArg = args[3] as Long
            val endMinArg = args[4] as Long
            val wrapped: List<Any?> = try {
              api.setPushTime(weekDaysArg, startHourArg, startMinArg, endHourArg, endMinArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.getRegId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getRegId{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.registerToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val appKeyArg = args[0] as String
            val appSecretArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.registerToken(appKeyArg, appSecretArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.unregisterToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.unregisterToken()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.openNotificationSetting$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.openNotificationSetting()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.getNotificationStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.getNotificationStatus()
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.enableAppNotificationSwitch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.enableAppNotificationSwitch{ result: Result<NotificationStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.disableAppNotificationSwitch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.disableAppNotificationSwitch{ result: Result<NotificationStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.getAppNotificationSwitch$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getAppNotificationSwitch{ result: Result<NotificationStatus> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.oppo_push.PushInterface.isSupport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.isSupport{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class MessagesPigeonStreamHandler<T>(
    val wrapper: MessagesPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface MessagesPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/** 所有回调都需要根据responseCode来判断操作是否成功，0代表成功,其他代码失败，失败具体原因可以查阅附录中的错误码列表, https://open.oppomobile.com/documentation/page/info?id=11224 */
abstract class StreamEventsStreamHandler : MessagesPigeonEventChannelWrapper<PlatformEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StreamEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.oppo_push.PushCallBackEventChannel.streamEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = MessagesPigeonStreamHandler<PlatformEvent>(streamHandler)
      EventChannel(messenger, channelName, MessagesPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
